Filter properties
samwho/obsidian-wikidata-importer pull request #12
Opened 2024-06-27 07:59 UTC by smor

This update allows filtering properties to import with two antagonist filtering strategies:
- whitelist : only retain matching properties;
- blacklist : exclude those properties from this list, and exclude everything else.

## Demo

https://github.com/samwho/obsidian-wikidata-importer/assets/39006/65327045-65ab-4ca9-a68a-efb842730628

Closes #7

2024-06-29 09:14 UTC, samwho requested changes
@smor thanks so much for your recent contributions. I'm happy to merge this one, but would ask before doing so that we change `whitelist` to `allowedProperties` and `blacklist` to `blockedProperties` 🙏

2024-07-01 09:21 UTC, smor commented
Hi @samwho, I updated the plugin as requested.

2024-07-01 19:45 UTC, samwho approved these changes

2024-07-01 19:45 UTC, merged

2024-07-01 19:45 UTC, samwho commented
Fantastic, thank you so much!